"""phase1 schema overhaul

Revision ID: phase1_schema_overhaul
Revises: 7f60891796d2
Create Date: 2026-05-17

Overview
--------
- Drop legacy reviews + review_photos (replaced by new 6-score reviews schema).
- Drop legacy pet-policy-ish columns from places (moved to pet_policies):
  allows_indoor, allows_outdoor, max_weight_kg, is_verified.
- Add new columns to places: road_address, visibility_status (enum),
  kakao_place_id, naver_place_id, official_mfds_id.
- Create new tables:
  pet_policies, correction_requests, reviews (new), owner_claims,
  policy_change_logs, place_matching_jobs, place_ratings.

This migration is written by hand (not autogenerated) so the destructive
drop/recreate order is explicit and round-trippable.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PGEnum


revision: str = "phase1_schema_overhaul"
down_revision: Union[str, Sequence[str], None] = "7f60891796d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ─── Enum definitions ───
# We use the postgresql.ENUM type with create_type=False so SQLAlchemy never
# auto-emits CREATE TYPE on column / table creation. Enums are created via
# raw SQL below (Step 3) and dropped via raw SQL in downgrade.
visibility_status_enum = PGEnum(
    "visible", "hidden", name="visibilitystatus", create_type=False,
)
pet_allowed_status_enum = PGEnum(
    "allowed", "limited", "not_allowed", "unknown",
    name="petallowedstatus", create_type=False,
)
verification_status_enum = PGEnum(
    "official_verified", "owner_verified", "admin_verified",
    "user_reported", "under_review", "unknown",
    name="verificationstatus", create_type=False,
)
policy_source_enum = PGEnum(
    "mfds", "owner", "admin", "user_report", "external", "unknown",
    name="policysource", create_type=False,
)
correction_request_status_enum = PGEnum(
    "pending", "reviewing", "approved", "rejected",
    name="correctionrequeststatus", create_type=False,
)
owner_claim_status_enum = PGEnum(
    "pending", "verified", "rejected",
    name="ownerclaimstatus", create_type=False,
)
place_matching_status_enum = PGEnum(
    "auto_matched", "pending_review", "unmatched", "approved", "rejected",
    name="placematchingstatus", create_type=False,
)


_CREATE_ENUM_SQL = [
    "CREATE TYPE visibilitystatus AS ENUM ('visible', 'hidden')",
    "CREATE TYPE petallowedstatus AS ENUM ('allowed', 'limited', 'not_allowed', 'unknown')",
    (
        "CREATE TYPE verificationstatus AS ENUM ("
        "'official_verified', 'owner_verified', 'admin_verified', "
        "'user_reported', 'under_review', 'unknown')"
    ),
    (
        "CREATE TYPE policysource AS ENUM ("
        "'mfds', 'owner', 'admin', 'user_report', 'external', 'unknown')"
    ),
    "CREATE TYPE correctionrequeststatus AS ENUM ('pending', 'reviewing', 'approved', 'rejected')",
    "CREATE TYPE ownerclaimstatus AS ENUM ('pending', 'verified', 'rejected')",
    (
        "CREATE TYPE placematchingstatus AS ENUM ("
        "'auto_matched', 'pending_review', 'unmatched', 'approved', 'rejected')"
    ),
]

_DROP_ENUM_SQL = [
    "DROP TYPE IF EXISTS placematchingstatus",
    "DROP TYPE IF EXISTS ownerclaimstatus",
    "DROP TYPE IF EXISTS correctionrequeststatus",
    "DROP TYPE IF EXISTS policysource",
    "DROP TYPE IF EXISTS verificationstatus",
    "DROP TYPE IF EXISTS petallowedstatus",
    "DROP TYPE IF EXISTS visibilitystatus",
]


def upgrade() -> None:
    bind = op.get_bind()

    # ── 1. Drop legacy review tables (CASCADE clears FK from review_photos) ──
    op.drop_table("review_photos")
    op.drop_table("reviews")

    # ── 2. Drop legacy pet-policy-ish columns from places ──
    op.drop_column("places", "allows_indoor")
    op.drop_column("places", "allows_outdoor")
    op.drop_column("places", "max_weight_kg")
    op.drop_column("places", "is_verified")

    # ── 3. Create all enums explicitly via raw SQL. We disabled create_type
    #       on the Enum objects so neither add_column nor create_table will
    #       try to issue CREATE TYPE itself, avoiding double-create. ──
    for stmt in _CREATE_ENUM_SQL:
        op.execute(stmt)

    # ── 4. Add new columns to places ──
    op.add_column("places", sa.Column("road_address", sa.String(500), nullable=True))
    op.add_column(
        "places",
        sa.Column(
            "visibility_status",
            visibility_status_enum,
            server_default="visible",
            nullable=False,
        ),
    )
    op.add_column("places", sa.Column("kakao_place_id", sa.String(100), nullable=True))
    op.add_column("places", sa.Column("naver_place_id", sa.String(100), nullable=True))
    op.add_column("places", sa.Column("official_mfds_id", sa.String(100), nullable=True))
    op.create_index("ix_places_visibility_status", "places", ["visibility_status"])
    op.create_index("ix_places_kakao_place_id", "places", ["kakao_place_id"])
    op.create_index("ix_places_naver_place_id", "places", ["naver_place_id"])
    op.create_index("ix_places_official_mfds_id", "places", ["official_mfds_id"])

    # ── 5. pet_policies ──
    op.create_table(
        "pet_policies",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "place_id", sa.Integer(),
            sa.ForeignKey("places.id", ondelete="CASCADE"),
            nullable=False, unique=True,
        ),
        sa.Column(
            "pet_allowed_status", pet_allowed_status_enum,
            server_default="unknown", nullable=False,
        ),
        sa.Column(
            "verification_status", verification_status_enum,
            server_default="unknown", nullable=False,
        ),
        sa.Column("indoor_allowed", sa.Boolean(), nullable=True),
        sa.Column("outdoor_allowed", sa.Boolean(), nullable=True),
        sa.Column("dog_allowed", sa.Boolean(), nullable=True),
        sa.Column("cat_allowed", sa.Boolean(), nullable=True),
        sa.Column("max_weight_kg", sa.Float(), nullable=True),
        sa.Column("leash_required", sa.Boolean(), nullable=True),
        sa.Column("carrier_required", sa.Boolean(), nullable=True),
        sa.Column("vaccination_required", sa.Boolean(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "policy_source", policy_source_enum,
            server_default="unknown", nullable=False,
        ),
        sa.Column("confidence_score", sa.Float(), server_default="0.0", nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_pet_policies_place_id", "pet_policies", ["place_id"])
    op.create_index(
        "ix_pet_policies_pet_allowed_status", "pet_policies", ["pet_allowed_status"]
    )
    op.create_index(
        "ix_pet_policies_verification_status", "pet_policies", ["verification_status"]
    )

    # ── 6. correction_requests ──
    op.create_table(
        "correction_requests",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "place_id", sa.Integer(),
            sa.ForeignKey("places.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "user_id", sa.Integer(),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("request_type", sa.String(50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("current_info", sa.JSON(), nullable=True),
        sa.Column("requested_info", sa.JSON(), nullable=True),
        # NOTE: evidence_image_url reserved for Phase 2.5 Object Storage uploads.
        sa.Column("evidence_image_url", sa.String(500), nullable=True),
        sa.Column("visit_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status", correction_request_status_enum,
            server_default="pending", nullable=False,
        ),
        sa.Column("admin_note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_correction_requests_place_id", "correction_requests", ["place_id"])
    op.create_index("ix_correction_requests_user_id", "correction_requests", ["user_id"])
    op.create_index("ix_correction_requests_status", "correction_requests", ["status"])

    # ── 7. reviews (new schema) ──
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "place_id", sa.Integer(),
            sa.ForeignKey("places.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "user_id", sa.Integer(),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("pet_visit_verified", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("pet_allowed_actual", sa.Boolean(), nullable=True),
        sa.Column("indoor_actual", sa.Boolean(), nullable=True),
        sa.Column("outdoor_actual", sa.Boolean(), nullable=True),
        sa.Column("pet_friendliness_score", sa.Float(), nullable=True),
        sa.Column("taste_score", sa.Float(), nullable=True),
        sa.Column("ambience_score", sa.Float(), nullable=True),
        sa.Column("cleanliness_score", sa.Float(), nullable=True),
        sa.Column("staff_friendliness_score", sa.Float(), nullable=True),
        sa.Column("revisit_intent_score", sa.Float(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("visit_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_reviews_place_id", "reviews", ["place_id"])
    op.create_index("ix_reviews_user_id", "reviews", ["user_id"])

    # ── 8. owner_claims ──
    op.create_table(
        "owner_claims",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "place_id", sa.Integer(),
            sa.ForeignKey("places.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "owner_user_id", sa.Integer(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("verification_method", sa.String(50), nullable=False),
        sa.Column(
            "verification_status", owner_claim_status_enum,
            server_default="pending", nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_owner_claims_place_id", "owner_claims", ["place_id"])
    op.create_index("ix_owner_claims_owner_user_id", "owner_claims", ["owner_user_id"])
    op.create_index(
        "ix_owner_claims_verification_status", "owner_claims", ["verification_status"]
    )

    # ── 9. policy_change_logs ──
    op.create_table(
        "policy_change_logs",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "place_id", sa.Integer(),
            sa.ForeignKey("places.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("field_name", sa.String(100), nullable=False),
        sa.Column("before_value", sa.Text(), nullable=True),
        sa.Column("after_value", sa.Text(), nullable=True),
        sa.Column("changed_by", sa.String(100), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_policy_change_logs_place_id", "policy_change_logs", ["place_id"])

    # ── 10. place_matching_jobs ──
    op.create_table(
        "place_matching_jobs",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "place_id", sa.Integer(),
            sa.ForeignKey("places.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("mfds_id", sa.String(100), nullable=False),
        sa.Column("kakao_id", sa.String(100), nullable=True),
        sa.Column("naver_id", sa.String(100), nullable=True),
        sa.Column("match_score", sa.Float(), server_default="0.0", nullable=False),
        sa.Column(
            "status", place_matching_status_enum,
            server_default="unmatched", nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.String(100), nullable=True),
    )
    op.create_index("ix_place_matching_jobs_place_id", "place_matching_jobs", ["place_id"])
    op.create_index("ix_place_matching_jobs_mfds_id", "place_matching_jobs", ["mfds_id"])
    op.create_index("ix_place_matching_jobs_status", "place_matching_jobs", ["status"])

    # ── 11. place_ratings (one row per place) ──
    op.create_table(
        "place_ratings",
        sa.Column(
            "place_id", sa.Integer(),
            sa.ForeignKey("places.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("pet_friendliness_avg", sa.Float(), server_default="0.0", nullable=False),
        sa.Column("taste_avg", sa.Float(), server_default="0.0", nullable=False),
        sa.Column("ambience_avg", sa.Float(), server_default="0.0", nullable=False),
        sa.Column("cleanliness_avg", sa.Float(), server_default="0.0", nullable=False),
        sa.Column(
            "staff_friendliness_avg", sa.Float(),
            server_default="0.0", nullable=False,
        ),
        sa.Column("revisit_intent_avg", sa.Float(), server_default="0.0", nullable=False),
        sa.Column("sample_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )


def downgrade() -> None:
    bind = op.get_bind()

    # Drop new tables in reverse FK-safe order.
    op.drop_table("place_ratings")
    op.drop_index("ix_place_matching_jobs_status", table_name="place_matching_jobs")
    op.drop_index("ix_place_matching_jobs_mfds_id", table_name="place_matching_jobs")
    op.drop_index("ix_place_matching_jobs_place_id", table_name="place_matching_jobs")
    op.drop_table("place_matching_jobs")
    op.drop_index("ix_policy_change_logs_place_id", table_name="policy_change_logs")
    op.drop_table("policy_change_logs")
    op.drop_index("ix_owner_claims_verification_status", table_name="owner_claims")
    op.drop_index("ix_owner_claims_owner_user_id", table_name="owner_claims")
    op.drop_index("ix_owner_claims_place_id", table_name="owner_claims")
    op.drop_table("owner_claims")
    op.drop_index("ix_reviews_user_id", table_name="reviews")
    op.drop_index("ix_reviews_place_id", table_name="reviews")
    op.drop_table("reviews")
    op.drop_index("ix_correction_requests_status", table_name="correction_requests")
    op.drop_index("ix_correction_requests_user_id", table_name="correction_requests")
    op.drop_index("ix_correction_requests_place_id", table_name="correction_requests")
    op.drop_table("correction_requests")
    op.drop_index("ix_pet_policies_verification_status", table_name="pet_policies")
    op.drop_index("ix_pet_policies_pet_allowed_status", table_name="pet_policies")
    op.drop_index("ix_pet_policies_place_id", table_name="pet_policies")
    op.drop_table("pet_policies")

    # Reverse places column adds.
    op.drop_index("ix_places_official_mfds_id", table_name="places")
    op.drop_index("ix_places_naver_place_id", table_name="places")
    op.drop_index("ix_places_kakao_place_id", table_name="places")
    op.drop_index("ix_places_visibility_status", table_name="places")
    op.drop_column("places", "official_mfds_id")
    op.drop_column("places", "naver_place_id")
    op.drop_column("places", "kakao_place_id")
    op.drop_column("places", "visibility_status")
    op.drop_column("places", "road_address")

    # Drop enums (after all dependent columns/tables are gone).
    for stmt in _DROP_ENUM_SQL:
        op.execute(stmt)

    # Restore legacy places columns.
    op.add_column(
        "places",
        sa.Column("is_verified", sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    op.add_column(
        "places",
        sa.Column("max_weight_kg", sa.Float(), nullable=True),
    )
    op.add_column(
        "places",
        sa.Column("allows_outdoor", sa.Boolean(), server_default=sa.true(), nullable=False),
    )
    op.add_column(
        "places",
        sa.Column("allows_indoor", sa.Boolean(), server_default=sa.false(), nullable=False),
    )

    # Restore legacy reviews + review_photos so downgrade is fully round-trip-able.
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "place_id", sa.Integer(),
            sa.ForeignKey("places.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "user_id", sa.Integer(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "pet_id", sa.Integer(),
            sa.ForeignKey("pets.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("visit_date", sa.String(20), nullable=True),
        sa.Column("is_helpful_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_verified_visit", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_reviews_place_id", "reviews", ["place_id"])
    op.create_index("ix_reviews_user_id", "reviews", ["user_id"])

    op.create_table(
        "review_photos",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "review_id", sa.Integer(),
            sa.ForeignKey("reviews.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("url", sa.String(500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_review_photos_review_id", "review_photos", ["review_id"])
